# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE=https://openapi.blofin.com
      - NUXT_PUBLIC_WS_PUBLIC=wss://openapi.blofin.com/ws/public
      - NUXT_PUBLIC_WS_PRIVATE=wss://openapi.blofin.com/ws/private
      - NUXT_API_KEY=${BLOFIN_API_KEY}
      - NUXT_SECRET_KEY=${BLOFIN_SECRET_KEY}
      - NUXT_PASSPHRASE=${BLOFIN_PASSPHRASE}
    networks:
      - blofin-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - blofin-network

volumes:
  redis-data:

networks:
  blofin-network:
    driver: bridge
